language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.3
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-23
    - android-22

    # Additional components
    - extra-google-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23
    # - sys-img-armeabi-v7a-android-17
