appId: com.duckduckgo.mobile.android
androidWebViewHierarchy: devtools
name: "Input Screen Chat Suggestions test"
tags:
  - inputScreenTest
  - chatSuggestionsTest
---
- retry:
    maxRetries: 3
    commands:
      - launchApp:
          clearState: true
          stopApp: true
      - runFlow: ../shared/skip_all_onboarding.yaml
      - runFlow: ./shared/input_screen_enable_flow.yaml
      - runFlow: ./shared/input_screen_chat_suggestions_flow.yaml
