name: 'End to End Tests - Full Suite (Nightly)'

on:
  schedule:
    - cron: '0 3 * * *' # run at 3 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumentation_tests:
    runs-on: ubuntu-latest
    name: End-to-End tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK version
        uses: actions/setup-java@v4
        with:
          java-version-file: .github/.java-version
          distribution: 'adopt'

      - name: Create folder
        if: always()
        run: mkdir apk

      - name: Decode keys
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_PROPERTIES }}
          fileName: ddg_android_build.properties
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Decode key file
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_KEY }}
          fileName: android
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Assemble release APK
        run: ./gradlew assemblePlayRelease -Pforce-default-variant -Pskip-onboarding

      - name: Move APK to new folder
        if: always()
        run: find . -name "*play-release*.apk" -exec mv '{}' apk/release.apk \;

      - name: Assemble internal release APK
        run: ./gradlew assembleInternalRelease -Pforce-default-variant -Pskip-onboarding

      - name: Move APK to new folder
        if: always()
        run: find . -name "*internal-release*.apk" -exec mv '{}' apk/internal.apk \;

      - name: Onboarding flows
        id: maestro-onboarding
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_test_name: onboardingTest_${{ github.sha }}
          maestro_app_file: apk/release.apk
          maestro_api_level: 30
          maestro_include_tags: onboardingTest
          test_suite_name: Onboarding (Nightly)
          is_release_blocker: 'true'

      - name: Deeplink tests
        id: maestro-deeplink
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_test_name: navigationTest_${{ github.sha }}
          maestro_app_file: apk/release.apk
          maestro_api_level: 30
          maestro_include_tags: navigationTest
          test_suite_name: Deeplink (Nightly)
          is_release_blocker: 'true'

      - name: Ad click detection flows
        id: maestro-ad-click
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_test_name: adClickTest_${{ github.sha }}
          maestro_app_file: apk/release.apk
          maestro_api_level: 30
          maestro_include_tags: adClickTest
          test_suite_name: Ad Click (Nightly)
          is_release_blocker: 'true'

      - name: Privacy Tests
        id: maestro-privacy
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_test_name: privacyTest_${{ github.sha }}
          maestro_app_file: apk/release.apk
          maestro_api_level: 30
          maestro_include_tags: privacyTest
          test_suite_name: Privacy (Nightly)
          is_release_blocker: 'true'

      - name: Internal Privacy Tests
        id: maestro-internal-privacy
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_test_name: internalPrivacyTest_${{ github.sha }}
          maestro_app_file: apk/internal.apk
          maestro_api_level: 34
          maestro_include_tags: privacyTestInternal
          test_suite_name: Internal Privacy (Nightly)
          is_release_blocker: 'true'

      - name: Security Tests
        id: maestro-security
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_test_name: securityTest_${{ github.sha }}
          maestro_app_file: apk/release.apk
          maestro_api_level: 30
          maestro_include_tags: securityTest
          test_suite_name: Security (Nightly)
          is_release_blocker: 'true'

      - name: Internal Security Tests
        id: maestro-internal-security
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_test_name: internalSecurityTest_${{ github.sha }}
          maestro_app_file: apk/internal.apk
          maestro_api_level: 30
          maestro_include_tags: securityTestInternal
          test_suite_name: Internal Security (Nightly)
          is_release_blocker: 'true'

      - name: Release Tests
        id: maestro-release
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_test_name: releaseTest_${{ github.sha }}
          maestro_app_file: apk/release.apk
          maestro_api_level: 30
          maestro_include_tags: releaseTest
          test_suite_name: Release Tests (Nightly)
          is_release_blocker: 'true'

      - name: Notifications permissions Android 13+
        id: maestro-notification-permissions
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_test_name: notificationPermissionTest_${{ github.sha }}
          maestro_app_file: apk/release.apk
          maestro_api_level: 33
          maestro_include_tags: permissionsTest
          test_suite_name: Notification Permissions (Nightly)
          is_release_blocker: 'true'

      - name: Create Asana task when workflow failed
        if: ${{ failure() }}
        id: create-failure-task
        uses: duckduckgo/native-github-asana-sync@v2.0
        with:
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-project: ${{ secrets.GH_ASANA_AOR_PROJECT_ID }}
          asana-section: ${{ secrets.GH_ASANA_INCOMING_ID }}
          asana-task-name: GH Workflow Failure - End to End tests (Full Suite)
          asana-task-description: The end to end workflow has failed. See https://github.com/duckduckgo/Android/actions/runs/${{ github.run_id }}
          action: 'create-asana-task'
