name: 'End to End Tests - Full Suite (Nightly)'

on:
  workflow_call:
    inputs:
      commit:
        description: 'Specific commit SHA to checkout (optional, defaults to latest)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      commit:
        description: 'Specific commit SHA to checkout (optional, defaults to latest)'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumentation_tests:
    runs-on: ubuntu-latest
    name: End-to-End tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Assemble APKs
        id: assemble
        uses: ./.github/actions/checkout-and-assemble
        with:
          commit: ${{ inputs.commit }}
          release_properties: ${{ secrets.FAKE_RELEASE_PROPERTIES }}
          release_key: ${{ secrets.FAKE_RELEASE_KEY }}
          gradle_encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          develocity_access_key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

      - name: Upload Internal Binary to Maestro
        id: maestro-upload-internal-binary
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: binary_internal_upload_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_file: ${{ steps.assemble.outputs.internal_apk_path }}
          maestro_api_level: 30
          maestro_include_tags: binaryUpload
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Internal Binary Upload

      - name: Upload Release Binary to Maestro
        id: maestro-upload-release-binary
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: binary_release_upload_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_file: ${{ steps.assemble.outputs.play_apk_path }}
          maestro_api_level: 30
          maestro_include_tags: binaryUpload
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Release Binary Upload

      - name: Custom tabs flows
        id: maestro-custom-tabs
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: customTabs_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_binary_id: ${{ steps.maestro-upload-internal-binary.outputs.maestro_app_binary_id }}
          maestro_api_level: 30
          maestro_include_tags: customTabsTest
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Custom Tabs
          is_release_blocker: 'true'
          asana_releases_project_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_ID }}
          asana_releases_blocker_section_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_BLOCKER_SECTION_ID }}

      - name: Internal Privacy Tests
        id: maestro-internal-privacy
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: internalPrivacyTest_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_binary_id: ${{ steps.maestro-upload-internal-binary.outputs.maestro_app_binary_id }}
          maestro_api_level: 34
          maestro_include_tags: privacyTestInternal
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Internal Privacy (Nightly)
          is_release_blocker: 'true'
          asana_releases_project_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_ID }}
          asana_releases_blocker_section_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_BLOCKER_SECTION_ID }}

      - name: Internal Security Tests
        id: maestro-internal-security
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: internalSecurityTest_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_binary_id: ${{ steps.maestro-upload-internal-binary.outputs.maestro_app_binary_id }}
          maestro_api_level: 30
          maestro_include_tags: securityTestInternal
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Internal Security (Nightly)
          is_release_blocker: 'true'
          asana_releases_project_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_ID }}
          asana_releases_blocker_section_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_BLOCKER_SECTION_ID }}

      - name: Onboarding flows
        id: maestro-onboarding
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: onboardingTest_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_binary_id: ${{ steps.maestro-upload-release-binary.outputs.maestro_app_binary_id }}
          maestro_api_level: 30
          maestro_include_tags: onboardingTest
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Onboarding (Nightly)
          is_release_blocker: 'true'
          asana_releases_project_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_ID }}
          asana_releases_blocker_section_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_BLOCKER_SECTION_ID }}

      - name: Deeplink tests
        id: maestro-deeplink
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: navigationTest_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_binary_id: ${{ steps.maestro-upload-release-binary.outputs.maestro_app_binary_id }}
          maestro_api_level: 30
          maestro_include_tags: navigationTest
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Deeplink (Nightly)
          is_release_blocker: 'true'
          asana_releases_project_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_ID }}
          asana_releases_blocker_section_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_BLOCKER_SECTION_ID }}

      - name: Ad click detection flows
        id: maestro-ad-click
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: adClickTest_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_binary_id: ${{ steps.maestro-upload-release-binary.outputs.maestro_app_binary_id }}
          maestro_api_level: 30
          maestro_include_tags: adClickTest
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Ad Click (Nightly)
          is_release_blocker: 'true'
          asana_releases_project_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_ID }}
          asana_releases_blocker_section_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_BLOCKER_SECTION_ID }}

      - name: Privacy Tests
        id: maestro-privacy
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: privacyTest_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_binary_id: ${{ steps.maestro-upload-release-binary.outputs.maestro_app_binary_id }}
          maestro_api_level: 30
          maestro_include_tags: privacyTest
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Privacy (Nightly)
          is_release_blocker: 'true'
          asana_releases_project_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_ID }}
          asana_releases_blocker_section_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_BLOCKER_SECTION_ID }}

      - name: Security Tests
        id: maestro-security
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: securityTest_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_binary_id: ${{ steps.maestro-upload-release-binary.outputs.maestro_app_binary_id }}
          maestro_api_level: 30
          maestro_include_tags: securityTest
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Security (Nightly)
          is_release_blocker: 'true'
          asana_releases_project_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_ID }}
          asana_releases_blocker_section_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_BLOCKER_SECTION_ID }}

      - name: Release Tests
        id: maestro-release
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: releaseTest_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_binary_id: ${{ steps.maestro-upload-release-binary.outputs.maestro_app_binary_id }}
          maestro_api_level: 30
          maestro_include_tags: releaseTest
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Release Tests (Nightly)
          is_release_blocker: 'true'
          asana_releases_project_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_ID }}
          asana_releases_blocker_section_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_BLOCKER_SECTION_ID }}

      - name: Notifications permissions Android 13+
        id: maestro-notification-permissions
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: notificationPermissionTest_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_binary_id: ${{ steps.maestro-upload-release-binary.outputs.maestro_app_binary_id }}
          maestro_api_level: 33
          maestro_include_tags: permissionsTest
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Notification Permissions (Nightly)
          is_release_blocker: 'true'
          asana_releases_project_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_ID }}
          asana_releases_blocker_section_id: ${{ vars.GH_ANDROID_APP_RELEASES_PROJECT_BLOCKER_SECTION_ID }}

      - name: Create Asana task when workflow failed
        if: ${{ failure() }}
        id: create-failure-task
        uses: duckduckgo/native-github-asana-sync@v2.0
        with:
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-project: ${{ secrets.GH_ASANA_AOR_PROJECT_ID }}
          asana-section: ${{ secrets.GH_ASANA_INCOMING_ID }}
          asana-task-name: GH Workflow Failure - End to End tests (Full Suite)
          asana-task-description: The end to end workflow has failed. See https://github.com/duckduckgo/Android/actions/runs/${{ github.run_id }}
          action: 'create-asana-task'
