name: 'End to End Tests - Omnibar (Nightly)'

on:
  schedule:
    - cron: '0 7 * * *' # run at 7 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumentation_tests:
    runs-on: ubuntu-latest
    name: End-to-End tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Assemble APKs
        id: assemble
        uses: ./.github/actions/checkout-and-assemble
        with:
          flavours: 'play'
          release_properties: ${{ secrets.FAKE_RELEASE_PROPERTIES }}
          release_key: ${{ secrets.FAKE_RELEASE_KEY }}
          gradle_encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          develocity_access_key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

      - name: Run Omnibar Maestro Tests
        id: maestro-cloud-asana
        uses: ./.github/actions/maestro-cloud-asana-reporter
        timeout-minutes: 120
        with:
          maestro_api_key: ${{ secrets.ROBIN_API_KEY }}
          maestro_project_id: ${{ vars.ROBIN_ANDROID_PROJECT_ID }}
          maestro_test_name: omnibar_${{ github.sha }}
          maestro_timeout: ${{ vars.ROBIN_TIMEOUT_MINUTES }}
          maestro_app_file: ${{ steps.assemble.outputs.play_apk_path }}
          maestro_include_tags: omnibarTest
          asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana_project_id: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana_section_id: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          test_suite_name: Omnibar

      - name: Create Asana task when workflow failed
        if: ${{ failure() && steps.maestro-cloud-asana.outputs.flow_summary_status != 'failure' }}
        uses: duckduckgo/native-github-asana-sync@v2.0
        with:
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-project: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana-section: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          asana-task-name: GH Workflow Failure - Omnibar End to End Tests (Nightly)
          asana-task-description: The Omnibar end-to-end workflow has failed. See https://github.com/duckduckgo/Android/actions/runs/${{ github.run_id }}
          action: 'create-asana-task'
