name: Nightly orchestrator

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-current-timestamp:
    name: Get current timestamp
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - name: Get current timestamp
        id: timestamp
        run: |
          echo "timestamp=$(date -u +'%Y-%m-%dT%H%M%S')" >> "$GITHUB_OUTPUT"

  get-tasks-waiting-for-release:
    name: Get tasks waiting for release
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.list-waiting.outputs.waiting-for-release }}
    steps:
      - name: Install Release Bridge from Homebrew
        run: |
          brew tap cdrussell/aarb
          brew install aarb
      - name: Get tasks waiting for release
        id: list-waiting
        run: |
          echo "waiting-for-release=$(AndroidAsanaBridge action=listPendingTasksGid | grep -E '^[0-9]+(,[0-9]+)*$')" >> "$GITHUB_OUTPUT"

  resolve-commit:
    name: Resolve commit SHA
    runs-on: android-large-runner
    outputs:
      commit_sha: ${{ steps.resolve.outputs.commit_sha }}
    steps:
      - name: Resolve commit SHA
        id: resolve
        run: |
          echo "Using commit: ${{ github.sha }}"
          echo "commit_sha=${{ github.sha }}" >> "$GITHUB_OUTPUT"

  call-nightly:
    needs: resolve-commit
    uses: ./.github/workflows/nightly.yml
    with:
      commit: ${{ needs.resolve-commit.outputs.commit_sha }}
    secrets: inherit

  call-end-to-end:
    needs: [resolve-commit, call-nightly]
    uses: ./.github/workflows/e2e-nightly-full-suite.yml
    with:
      commit: ${{ needs.resolve-commit.outputs.commit_sha }}
    secrets: inherit

  call-privacy:
    needs: [ resolve-commit, call-end-to-end ]
    uses: ./.github/workflows/privacy.yml
    with:
      commit: ${{ needs.resolve-commit.outputs.commit_sha }}
    secrets: inherit

  call-update-content-scope:
    needs: [ resolve-commit, call-privacy ]
    uses: ./.github/workflows/update-content-scope.yml
    with:
      commit: ${{ needs.resolve-commit.outputs.commit_sha }}
    secrets: inherit

  call-update-ref-tests:
    needs: [ resolve-commit, call-update-content-scope ]
    uses: ./.github/workflows/update-ref-tests.yml
    with:
      commit: ${{ needs.resolve-commit.outputs.commit_sha }}
    secrets: inherit

  tag_lgc_when_successful:
    name: Tag last good commit when successful
    runs-on: ubuntu-latest
    needs: [ get-current-timestamp, get-tasks-waiting-for-release, resolve-commit, call-nightly, call-end-to-end, call-privacy, call-update-content-scope, call-update-ref-tests]
    if: ${{ success() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.resolve-commit.outputs.commit_sha }}
          fetch-depth: 0
          submodules: recursive

      - name: Set up git config
        run: |
          git remote set-url origin https://${{ secrets.GT_DAXMOBILE }}@github.com/duckduckgo/Android.git/
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Create tag
        run: |
          TAG_NAME="LGC-${{ needs.get-current-timestamp.outputs.timestamp }}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Install Release Bridge from Homebrew
        run: |
          brew tap cdrussell/aarb
          brew install aarb

      - name: Tag tasks waiting for release
        run: |
          AndroidAsanaBridge action=tagTasksFromList lgc=LGC-${{ needs.get-current-timestamp.outputs.timestamp }} tasks=${{ needs.get-tasks-waiting-for-release.outputs.timestamp }}